env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides:
  - files:
      - "*.ts"
    rules:
      '@typescript-eslint/no-undef': off
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - warn
    - single
  semi:
    - warn
    - never
  no-unused-vars: 
    - warn
